### ISSUE TITLE
Idea: Modules per part?

### ISSUE THREAD

**Issue by etcinit** [sellerlabs/haskell-workshop#5]
`Reddit.hs` is divided into 4 sections (Parts 1, 2, and 3, and internals). We could potentially divide these into modules, hiding internals in an Internal.hs module.

I propose this because:

- It provides an example of how to use modules (exporting and importing).
- During the workshop it might be easier to refer to a specific module and have a clean area of focus.

Drawback: Tiny modules might be excessive.

**Comment by etcinit** [comment]
Experimental version of this: #6.

**Comment by 5outh** [comment]
This is a reference implementation for us to work through with the attendees, not something we will be walking through and explaining. I would prefer for all newcomers to the language not to have to deal with creating new modules since it will just drag out the event.

What I would accept is pulling the `Internals` into a separate modules and importing them, since those will not be implemented by guests. We can use these as an example of importing/exporting. However, I think everything else should stay in place so we don't need to worry about jumping between files to explain everything. A single 100 line tutorial is easier to digest than a 3 part one.

**Comment by etcinit** [comment]
Ok
